const C = {
  AUTH_FETCHING: 'AUTH_FETCHING',
  AUTH_ERROR: 'AUTH_ERROR',
  SET_AUTH: 'SET_AUTH',
  RESET_AUTH: 'RESET_AUTH',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
}

export default C
